import { Property, Testimonial, BlogPost, Service } from './types'

export const properties: Property[] = [
  {
    id: '1',
    title: 'Platinum Enclave',
    location: 'Afrimart Atlantic, Accra',
    price: null,
    currency: 'USD',
    type: 'residential',
    bedrooms: null,
    bathrooms: null,
    sqft: null,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    ],
    description: 'Premium residential enclave in Afrimart Atlantic with modern amenities and excellent investment potential.',
    amenities: null,
    yearBuilt: null,
    roi: null,
    featured: true,
  },
  {
    id: '2',
    title: 'Avalon Enclave',
    location: 'Afrimart Atlantic, Accra',
    price: null,
    currency: 'USD',
    type: 'residential',
    bedrooms: null,
    bathrooms: null,
    sqft: null,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    ],
    description: 'Exclusive residential enclave offering comfort and prosperity for discerning buyers in Afrimart Atlantic.',
    amenities: null,
    yearBuilt: null,
    roi: null,
    featured: true,
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Kwame Mensah',
    title: 'Business Executive',
    location: 'London, UK',
    content: 'NovaNest made my investment journey seamless. The team\'s expertise and professionalism ensured I found the perfect property for my family.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
  },
  {
    id: '2',
    name: 'Ama Boateng',
    title: 'Real Estate Investor',
    location: 'Toronto, Canada',
    content: 'Outstanding service and attention to detail. They understood my investment goals and delivered exactly what I was looking for.',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80',
  },
  {
    id: '3',
    name: 'Kofi Asante',
    title: 'Entrepreneur',
    location: 'New York, USA',
    content: 'Professional, trustworthy, and results-driven. NovaNest is the partner you want when investing in Ghana\'s real estate.',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80',
  },
]

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    slug: 'ghana-real-estate-investment-guide',
    title: 'The Complete Guide to Real Estate Investment in Ghana',
    excerpt: 'Discover the key opportunities and strategic insights for investing in Ghana\'s booming real estate market.',
    content: 'Ghana\'s real estate sector is experiencing unprecedented growth, with diaspora investors leading the charge. This comprehensive guide covers market trends, investment strategies, and everything you need to know.',
    category: 'guide',
    author: 'Nana Kwesi',
    date: new Date('2024-02-15'),
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
    readTime: 8,
  },
  {
    id: '2',
    slug: 'diaspora-investment-opportunities',
    title: 'Why Diaspora Investment is Ghana\'s Future',
    excerpt: 'Explore the lucrative opportunities available to diaspora investors in Ghana\'s property market.',
    content: 'Diaspora investors have become a major force in Ghana\'s real estate development. Learn about the unique advantages and tax benefits available to non-resident investors.',
    category: 'diaspora',
    author: 'Abena Osei',
    date: new Date('2024-02-10'),
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
    readTime: 6,
  },
  {
    id: '3',
    slug: 'property-valuation-tips',
    title: 'How to Accurately Value a Property',
    excerpt: 'Master the essential techniques for property valuation to make informed investment decisions.',
    content: 'Understanding property valuation is crucial for any real estate investor. This article breaks down the key methods and factors that influence property values in Ghana.',
    category: 'tips',
    author: 'Yaw Boakye',
    date: new Date('2024-02-05'),
    image: 'https://images.unsplash.com/photo-1573136067063-aa936e17b8e6?w=800&q=80',
    readTime: 5,
  },
  {
    id: '4',
    slug: 'accra-property-market-trends-2024',
    title: 'Accra Property Market Trends 2024',
    excerpt: 'What\'s happening in Accra\'s real estate market this year and what it means for investors.',
    content: 'The Accra property market is showing strong growth indicators. Discover the hottest neighborhoods and emerging opportunities for 2024.',
    category: 'market',
    author: 'Esi Mensah',
    date: new Date('2024-01-28'),
    image: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&q=80',
    readTime: 7,
  },
]

export const services: Service[] = [
  {
    id: '1',
    title: 'Property Buying Assistance',
    description: 'Expert guidance to find the perfect property matching your investment criteria and budget.',
    icon: 'search',
  },
  {
    id: '2',
    title: 'Property Selling Services',
    description: 'Comprehensive support to market and sell your property effectively at the best price.',
    icon: 'clipboard',
  },
  {
    id: '3',
    title: 'Rental & Leasing Services',
    description: 'Management and placement services for rental properties and leasing arrangements.',
    icon: 'chart',
  },
  {
    id: '4',
    title: 'Property Management',
    description: 'Full property management services including maintenance, rentals, and tenant relations.',
    icon: 'home',
  },
  {
    id: '5',
    title: 'Real Estate Investment Advisory',
    description: 'Data-driven investment analysis and market insights for informed property decisions.',
    icon: 'trending',
  },
]
